gpio:
  pin: 23

cors:
  allow_origins:
    - "http://127.0.0.1"
    - "http://localhost"
    - "http://localhost:3000"
  # Regex to match any 192.168.1.x address (optionally with a port)
  # Modify with your own network settings if needed
  allow_origin_regex: "^http://192\\.168\\.1\\.[0-9]+(:[0-9]+)?$"
  allow_methods:
    - "*"
  allow_headers:
    - "*"